CREATE TABLE "work_types" (
  "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR(255) NOT NULL,
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT "work_types_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "measurement_units" (
  "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "name" VARCHAR(100) NOT NULL,
  "symbol" VARCHAR(20) NOT NULL,
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT "measurement_units_pkey" PRIMARY KEY ("id")
);

CREATE TABLE "work_log_entries" (
  "id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "work_date" DATE NOT NULL,
  "work_type_id" INTEGER NOT NULL,
  "measurement_unit_id" INTEGER NOT NULL,
  "volume" DECIMAL(10, 2) NOT NULL,
  "worker_name" VARCHAR(255) NOT NULL,
  "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updated_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

  CONSTRAINT "work_log_entries_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "work_types_name_key" ON "work_types"("name");
CREATE UNIQUE INDEX "measurement_units_name_key" ON "measurement_units"("name");
CREATE UNIQUE INDEX "measurement_units_symbol_key" ON "measurement_units"("symbol");
CREATE INDEX "work_log_entries_work_date_idx" ON "work_log_entries"("work_date");
CREATE INDEX "work_log_entries_work_type_id_idx" ON "work_log_entries"("work_type_id");
CREATE INDEX "work_log_entries_measurement_unit_id_idx" ON "work_log_entries"("measurement_unit_id");

ALTER TABLE "work_log_entries"
ADD CONSTRAINT "work_log_entries_work_type_id_fkey"
FOREIGN KEY ("work_type_id")
REFERENCES "work_types"("id")
ON DELETE RESTRICT
ON UPDATE CASCADE;

ALTER TABLE "work_log_entries"
ADD CONSTRAINT "work_log_entries_measurement_unit_id_fkey"
FOREIGN KEY ("measurement_unit_id")
REFERENCES "measurement_units"("id")
ON DELETE RESTRICT
ON UPDATE CASCADE;
